
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package net.darmo_creations.json.parser;

/** CUP generated class containing symbol constants. */
public class Tokens {
  /* terminals */
  public static final int COLON = 6;
  public static final int NUMBER = 8;
  public static final int BOOLEAN = 10;
  public static final int NULL = 11;
  public static final int STRING = 9;
  public static final int EOF = 0;
  public static final int RBRACKET = 5;
  public static final int error = 1;
  public static final int COMMA = 7;
  public static final int RCURLY = 3;
  public static final int LBRACKET = 4;
  public static final int LCURLY = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LCURLY",
  "RCURLY",
  "LBRACKET",
  "RBRACKET",
  "COLON",
  "COMMA",
  "NUMBER",
  "STRING",
  "BOOLEAN",
  "NULL"
  };
}

